/* drop table if exists zzz_event_configuration;

CREATE TABLE zzz_event_configuration
(
  id integer NOT NULL,
  created_by integer NOT NULL,
  created_on timestamp without time zone NOT NULL,
  modified_by integer,
  modified_on timestamp without time zone,
  day smallint,
  description character varying(1000),
  event_type character varying(100),
  event_type_detail_id integer,
  form_type_id integer,
  hour smallint,
  minute smallint,
  name character varying(500) NOT NULL,
  config_json text,
  state character varying(255),
  trigger_when character varying(50),
  event_type_detail_code character varying(200),
  uuid uuid,
  CONSTRAINT zzz_event_configuration_pkey PRIMARY KEY (id)
);

INSERT INTO zzz_event_configuration
(id, created_by, created_on, modified_by, modified_on, "day", description, event_type, event_type_detail_id, form_type_id, "hour", "minute", "name", config_json, state, trigger_when, event_type_detail_code, uuid)
values
(139, 74840, '2020-07-08 18:58:39.586', 84954, '2020-10-01 17:38:48.572', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging MotherANCService uploadMothers', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"af9854f3-1c03-41af-b4e1-bcbc0c397189","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":139,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":10,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '1fe16a9b-6c7e-4fc5-914d-f6b21240f5d0'),
(140, -1, '2020-06-26 12:04:45.816', 84954, '2020-10-01 17:42:18.988', NULL, NULL, 'TIMMER_BASED', NULL, NULL, NULL, 0, 'Imtstaging CroneService setSystemSyncConfig', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"ffc4f755-ab6b-4c78-9c4c-db21e314c740","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":140,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":20,"functionParams":[]}]}]}]', 'ACTIVE', 'HOURLY', NULL, '3d727f89-2b6d-4b8b-a7a3-9e78bf21e495'),
(141, -1, '2020-06-26 12:04:45.812', 84954, '2020-10-05 09:53:37.474', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 8, 0, 'Imtstaging CroneService dailyTipsNotificationsForMYTechoUsers', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"ae7d9834-fab5-4b31-8bdb-de86b69ff5f9","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":141,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":18,"functionParams":[]}]}]}]', 'INACTIVE', 'DAILY', NULL, '69fb5132-ac4e-4ece-9289-dc2798b97d1c'),
(142, -1, '2020-06-26 12:04:45.808', 84954, '2020-10-01 18:00:15.867', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 4, 0, 'Imtstaging CroneService updateAllActiveLocationsWithWorkerInfo', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"57af99fc-fe0c-4222-a084-905514f18220","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":142,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":17,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '47f00ca4-8777-444a-8388-360d52eac8ab'),
(143, -1, '2020-06-26 12:04:45.803', 84954, '2020-10-01 17:48:17.604', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging MotherPNCService upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"09fe9d33-4653-4aa2-9586-0e1961a0148d","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":143,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":14,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '6e2226f0-c79a-427b-b2bb-576a000a463e'),
(144, -1, '2020-06-26 12:04:45.799', 84954, '2020-10-01 17:49:05.685', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging MotherInfrantService upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"8e284041-d2cf-42be-b010-a916e975d421","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":144,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":12,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '48053de8-8afa-43b3-902e-c75f2d63007f'),
(145, -1, '2020-06-26 12:04:44.144', 84954, '2020-10-01 17:52:53.269', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging EligibleCoupleService uploadEligibleCouple', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"96691051-8237-492b-aa9e-2f8cc22e21be","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":145,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":8,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '6f600247-f909-4d3f-8e29-3da2ea04a1c7'),
(146, -1, '2020-06-26 12:04:44.140', 84954, '2020-10-01 17:53:37.829', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging ChildPNCService Upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"24613ec4-b975-41c0-a162-c0e241de08e8","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":146,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":4,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '8ff44f64-46a5-4bc9-9a31-0931d9b34edb'),
(147, -1, '2020-06-26 12:04:43.381', 84954, '2020-10-01 18:01:09.331', NULL, NULL, 'TIMMER_BASED', NULL, NULL, NULL, 0, 'Imtstaging CroneService checkRequestResponseList', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"b33155a6-1c8a-4de0-82dd-e8a0f5065f1f","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":147,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":19,"functionParams":[]}]}]}]', 'ACTIVE', 'MINUTE', NULL, '935486f5-060e-470d-a658-3912a06a2ac6'),
(148, -1, '2020-06-25 20:33:53.157', 1, '2020-09-24 14:03:44.200', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 23, 0, 'Imtstaging CroneService pushNcdDataToDell', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"63d0d6fd-0748-405e-a5b0-e493d1beb41e","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":null,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":19,"functionParams":[]}],"uuid":null,"isFromOtherServer":null}],"uuid":null,"isFromOtherServer":null}]', 'ACTIVE', 'DAILY', NULL, '73640b55-d837-47d8-8eb9-4aefd3bdd1f2'),
(149, -1, '2020-06-25 20:33:52.694', 1, '2020-09-24 14:03:44.200', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 2, 0, 'Imtstaging CroneService checkIfChildIsDefaulter', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"1c58dfbb-12b1-4c8e-ada3-c73fcb9f886a","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":null,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":18,"functionParams":[]}],"uuid":null,"isFromOtherServer":null}],"uuid":null,"isFromOtherServer":null}]', 'ACTIVE', 'DAILY', NULL, '7e5034c7-d47a-4e7d-88b9-d102b3fdf319'),
(150, -1, '2020-06-25 20:33:51.915', 1, '2020-09-24 14:03:44.200', NULL, NULL, 'TIMMER_BASED', NULL, NULL, NULL, 0, 'Imtstaging CroneService updateMaxRefreshCount', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"fbbd0d45-859f-41ff-8821-81a0ee3d62ae","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":null,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":16,"functionParams":[]}],"uuid":null,"isFromOtherServer":null}],"uuid":null,"isFromOtherServer":null}]', 'ACTIVE', 'MINUTE', NULL, '5f4f71c9-f0d8-4448-8651-66a38f8af7b1'),
(151, -1, '2020-06-25 20:33:46.095', 84954, '2020-10-01 17:54:00.343', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging MotherMadicalService uploadMothers', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"2f762504-2898-42a5-85f1-1fb5de03184f","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":151,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":13,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, 'c5ec6cbe-f247-4d8e-bdfb-158eb77b7a3e'),
(152, -1, '2020-06-25 20:33:44.710', 84954, '2020-10-01 17:54:19.262', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging MotherDeliveryService upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"27422702-aba9-4bfa-9a3e-9649d562b458","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":152,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":11,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '08ea8334-ba21-40df-984e-bccf0e10dbb3'),
(154, -1, '2020-06-25 20:31:34.161', 84954, '2020-10-01 17:54:38.076', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging EligibleCoupleTrackingService uploadEliginleCouple', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"3e5b860d-3ac5-4027-b73f-48f5d2f0c15b","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":154,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":9,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, 'efb69e5c-ccdf-49dd-b247-037b6b8f8c8d'),
(155, -1, '2020-06-25 20:31:32.724', 84954, '2020-10-01 17:54:56.418', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging ChildTrackingService Upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"e1083902-23a8-4857-a49a-23993c90bfe4","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":155,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":7,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, 'bfec889b-d4c2-44db-a464-22bdb8ee5c17'),
(156, -1, '2020-06-25 20:31:21.918', 84954, '2020-10-01 17:55:15.432', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging ChildTrackingMedicalService Upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"984417e9-b9ca-4a82-99a4-b00a25423108","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":156,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":6,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '47d79c8f-6908-4b8e-93df-bfc51269df58'),
(157, -1, '2020-06-25 20:31:21.250', 84954, '2020-10-01 17:55:32.677', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging ChildRegistrationService Upload', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"b3fa3cda-1f94-470f-9325-b92d95d27c01","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":157,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":5,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '340561df-e277-45af-9335-cf2719a2d076'),
(158, 80208, '2020-06-22 17:28:55.843', 1, '2020-09-24 14:03:44.200', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 3, 0, 'Imtstaging CroneService createTemporaryMemberForMigrationIn', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"02529ff1-3d2c-4e29-99a9-4a29a21fe930","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":null,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":20,"functionParams":[]}],"uuid":null,"isFromOtherServer":null}],"uuid":null,"isFromOtherServer":null}]', 'ACTIVE', 'DAILY', NULL, 'a53fdfa0-91f0-4d9d-b079-519c7b134314'),
(159, 80208, '2020-06-22 16:04:44.060', 84954, '2020-10-01 17:55:52.816', NULL, NULL, 'TIMMER_BASED', NULL, NULL, 10, 0, 'Imtstaging MotherRegistrationService uploadMothers', '[{"query":"select 1;","queryParam":null,"conditions":[{"isConditionReq":false,"condition":null,"conditionParam":null,"description":null,"notificaitonConfigsType":[{"id":"e8e60b79-eb58-4bda-b3c7-f1400aab55f9","type":"SYSTEM_FUNCTION","template":null,"mobileNotificationType":null,"mobileNotificationTypeUUID":null,"emailSubject":null,"emailSubjectParameter":null,"templateParameter":null,"baseDateFieldName":null,"refCode":null,"memberFieldName":null,"userFieldName":null,"familyFieldName":null,"trigerWhen":null,"day":null,"hour":null,"miniute":null,"mobileNotificationConfigs":null,"configId":159,"queryMasterId":null,"queryCode":null,"queryMasterParamJson":null,"exceptionType":null,"exceptionMessage":null,"smsConfigJson":null,"systemFunctionId":15,"functionParams":[]}]}]}]', 'ACTIVE', 'DAILY', NULL, '06925269-cb6a-4a0c-a119-fcc2dea156b8');


with event_ids as (
insert into event_configuration
(created_by, created_on, modified_by, modified_on, "day", description, event_type, event_type_detail_id, form_type_id, "hour", "minute", "name", config_json, state, trigger_when, event_type_detail_code, uuid)
select created_by, created_on, modified_by, modified_on, "day", description, event_type, event_type_detail_id, form_type_id, "hour", "minute", "name", config_json, state, trigger_when, event_type_detail_code, uuid
from zzz_event_configuration returning event_configuration.id
)
insert into timer_event
(event_config_id,processed,status,"type",system_trigger_on)
select id, false, 'NEW', 'TIMER_EVENT', now() from event_ids;

drop table if exists zzz_event_configuration;

*/

