drop table if exists ndhm_hp_id_user_details;
create table ndhm_hp_id_user_details (
	id serial,
	user_id Integer NOT NULL,
	hpr_id_number varchar(250) NOT NULL,
	hpr_id varchar(250),
	mobile varchar(250),
	first_name varchar(250),
    middle_name varchar(250),
    last_name varchar(250),
    name varchar(250),
    day_of_birth varchar(2),
    month_of_birth varchar(2),
    year_of_birth varchar(4),
    gender varchar(1),
    email varchar(250),
    kyc_photo bytea,
    profile_photo bytea,
    state_code varchar(50),
    state_name varchar(50),
    district_code varchar(50),
    district_name varchar(50),
    sub_district_code varchar(50),
    sub_district_name varchar(50),
    village_code varchar(50),
    village_name varchar(50),
    town_code varchar(50),
    town_name varchar(50),
    ward_code varchar(50),
    ward_name varchar(50),
    pincode varchar(50),
    address varchar(250),
    kyc_verified boolean,
    verification_type varchar(50),
    verification_status varchar(50),
    category_id Integer,
    category_name varchar(50),
    category_sub_id Integer,
    category_sub_name varchar(50),
    new boolean,
    email_verified boolean,
    created_by Integer NOT NULL,
    created_on timestamp without time zone NOT NULL,
    modified_by Integer,
    modified_on timestamp without time zone,
    CONSTRAINT ndhm_hp_id_user_details_pkey PRIMARY KEY(id)
);