alter table if exists listvalue_field_value_detail
add column if not exists additional_detail text;

insert into listvalue_field_master (field_key,field,is_active,field_type,form,role_type) values
	 ('translation_language','Language translation',true,'T','WEB','');

insert into listvalue_field_value_detail (
            is_active,
            is_archive,
            last_modified_by,
            last_modified_on,
            value,
            field_key,
            file_size,
            multimedia_type,
            code,
            additional_detail
        ) values (true,false,-1,now(),'Arabic','translation_language',0,null,'ar','{"Orientation": "right_to_left"}'),
(true,false,-1,now(),'Bulgarian','translation_language',0,null,'bg','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Bengali','translation_language',0,null,'bn','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Bosnian','translation_language',0,null,'bs','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Catalan','translation_language',0,null,'ca','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Montenegrin','translation_language',0,null,'cnr','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Czech','translation_language',0,null,'cs','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Welsh','translation_language',0,null,'cy','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Danish','translation_language',0,null,'da','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'German','translation_language',0,null,'de','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Greek','translation_language',0,null,'el','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'English','translation_language',0,null,'en','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Spanish','translation_language',0,null,'es','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Estonian','translation_language',0,null,'et','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Basque','translation_language',0,null,'eu','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Finnish','translation_language',0,null,'fi','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'French','translation_language',0,null,'fr','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'French (Canada)','translation_language',0,null,'fr-CA','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Irish','translation_language',0,null,'ga','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Gujarati','translation_language',0,null,'gu','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Hebrew','translation_language',0,null,'he','{"Orientation": "right_to_left"}'),
(true,false,-1,now(),'Hindi','translation_language',0,null,'hi','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Croatian','translation_language',0,null,'hr','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Hungarian','translation_language',0,null,'hu','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Indonesian','translation_language',0,null,'id','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Italian','translation_language',0,null,'it','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Japanese','translation_language',0,null,'ja','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Kannada','translation_language',0,null,'kn','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Korean','translation_language',0,null,'ko','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Lithuanian','translation_language',0,null,'lt','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Latvian','translation_language',0,null,'lv','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Malayalam','translation_language',0,null,'ml','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Marathi','translation_language',0,null,'mr','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Malay','translation_language',0,null,'ms','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Maltese','translation_language',0,null,'mt','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Norwegian Bokmal','translation_language',0,null,'nb','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Nepali','translation_language',0,null,'ne','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Dutch','translation_language',0,null,'nl','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Punjabi','translation_language',0,null,'pa','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Polish','translation_language',0,null,'pl','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Portuguese','translation_language',0,null,'pt','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Romanian','translation_language',0,null,'ro','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Russian','translation_language',0,null,'ru','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Sinhala','translation_language',0,null,'si','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Slovakian','translation_language',0,null,'sk','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Slovenian','translation_language',0,null,'sl','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Serbian','translation_language',0,null,'sr','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Swedish','translation_language',0,null,'sv','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Tamil','translation_language',0,null,'ta','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Telugu','translation_language',0,null,'te','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Thai','translation_language',0,null,'th','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Turkish','translation_language',0,null,'tr','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Ukrainian','translation_language',0,null,'uk','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Urdu','translation_language',0,null,'ur','{"Orientation": "right_to_left"}'),
(true,false,-1,now(),'Vietnamese','translation_language',0,null,'vi','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Simplified Chinese','translation_language',0,null,'zh','{"Orientation": "left_to_right"}'),
(true,false,-1,now(),'Traditional Chinese','translation_language',0,null,'zh-TW','{"Orientation": "left_to_right"}')
