
drop table if exists anemia_member_detail;
CREATE TABLE anemia_member_detail
(
	id serial primary key,
	member_id integer,
    service_date timestamp without time zone,
    inclusion1 boolean,
    inclusion2 boolean,
    inclusion3 boolean,
    inclusion4 boolean,
    inclusion_comment text,
    inclusion5 boolean,
    inclusion6 boolean,
    exclusion1 boolean,
    exclusion2 boolean,
    exclusion3 boolean,
    exclusion_comment text,
    eligibility_comment text,
    eligible boolean,
    not_eligible_reason text,
    clinical_setting_type text,
    visit_reason text,
    service_attended text,
    smoking_history text,
    lack_of_energy boolean,
    breath_shortness boolean,
    fast_heart_beat boolean,
    losing_weight boolean,
    chest_pain boolean,
    dizziness boolean,
    headache boolean,
    leg_cramp boolean,
    brittle_nail_hair boolean,
    adult_other_symptom text,
    child_looks_pale boolean,
    child_losing_weight boolean,
    child_tired boolean,
    child_breathing_difficulty boolean,
    child_other_symptom text,
    data_collection_place text,
    data_collection_location text,
    data_collection_time text,
    data_collection_season text,
    light_intensity text,
    infant_height integer,
    infant_weight integer,
    systolic_bp integer,
    diastolic_bp integer,
    skin_tone_l integer,
    skin_tone_b integer,
    nail_polish_or_henna boolean,
    nail_examination text,
    other_nail_examination text,
    finger_or_hand_examination text,
    other_finger_or_hand_examination text,
    eye_examination text,
    other_eye_examination text,
    tongue_examination text,
    ppg_data_collection text,
    hemocue integer,
    sickle_cell_disease text,
	latitude varchar(100) NULL,
	longitude varchar(100) NULL,
	mobile_start_date timestamp NOT NULL,
	mobile_end_date timestamp NOT NULL,
	created_on timestamp without time zone,
	modified_on timestamp without time zone,
	created_by integer,
	modified_by integer
);

drop table if exists member_survey_detail_master;
CREATE TABLE member_survey_detail_master
(
	id serial primary key,
	opd_id text,
    location_id integer,
    first_name text,
    middle_name text,
    last_name text,
    dob date,
    gender text,
    eligible_for_anemia boolean,
    caste text,
    religion text,
    occupation text,
    is_pregnant boolean,
    lmp date,
    mobile_number text,
	latitude varchar(100) NULL,
	longitude varchar(100) NULL,
	mobile_start_date timestamp NOT NULL,
	mobile_end_date timestamp NOT NULL,
	created_from text,
	created_on timestamp without time zone,
	created_by integer,
	modified_on timestamp without time zone,
	modified_by integer
);

drop table if exists anemia_protocol_deviation_detail;
CREATE TABLE anemia_protocol_deviation_detail
(
	id serial primary key,
	member_id integer,
    service_date timestamp without time zone,
    major_deviation text,
    other_major_deviation text,
    minor_deviation text,
    other_minor_deviation text,
    additional_comment text,
    result_in_ae boolean,
    participant_withdrawn_result boolean,
    reportable_to_irb boolean,
    reported_to_irb boolean,
    corrective_action_plan boolean,
    action_plan_description text,
    deviation_plan text,
    latitude varchar(100) NULL,
	longitude varchar(100) NULL,
	mobile_start_date timestamp NOT NULL,
	mobile_end_date timestamp NOT NULL,
	created_on timestamp without time zone,
	modified_on timestamp without time zone,
	created_by integer,
	modified_by integer
);


drop table if exists anemia_crf_detail;
CREATE TABLE anemia_crf_detail
(
	id serial primary key,
	member_id integer,
    service_date timestamp without time zone,
    event_detail text,
    event_date timestamp without time zone,
    event_time text,
    reported_date timestamp without time zone,
    severity text,
    treatment text,
    other_treatment text,
    relationship_to_study text,
    expected_flag boolean,
    reported_to_iec boolean,
    outcome text,
    resolution_description text,
    resolution_ongoing boolean,
    resolution_date timestamp without time zone,
    serious_ae_flag boolean,
    latitude varchar(100) NULL,
	longitude varchar(100) NULL,
	mobile_start_date timestamp NOT NULL,
	mobile_end_date timestamp NOT NULL,
	created_on timestamp without time zone,
	modified_on timestamp without time zone,
	created_by integer,
	modified_by integer
);