CREATE TABLE if not exists member_sickle_cell_survey_details (
   id SERIAL PRIMARY KEY,
   member_id INTEGER not null,
   family_id INTEGER not null,
   location_id INTEGER not null,
   service_date DATE not null,
   latitude character varying(100),
   longitude character varying(100),
   mobile_start_date timestamp without time zone NULL,
   mobile_end_date timestamp without time zone NULL,
   location_hierarchy_id int null,
   notification_id int null,
   residence_status VARCHAR(255),
   survey_availability_flag BOOLEAN,
   consent_given_flag BOOLEAN,
   bp_measured_flag BOOLEAN,
   high_bp_informed BOOLEAN,
   taking_bp_medicine BOOLEAN,
   systolic_bp INTEGER,
   diastolic_bp INTEGER,
   record_time_bp1 VARCHAR(255),
   systolic_bp2 INTEGER,
   diastolic_bp2 INTEGER,
   record_time_bp2 VARCHAR(255),
   earlier_diabetes_diagnosis BOOLEAN,
   diabetes_informed BOOLEAN,
   taking_diabetes_medicine BOOLEAN,
   last_eat_or_drink SMALLINT,
   blood_sugar INTEGER,
   earlier_oral_screened BOOLEAN,
   earlier_breast_screened BOOLEAN,
   earlier_cervical_screened BOOLEAN,
   suspected_cancer_detect BOOLEAN,
   had_biopsy BOOLEAN,
   mental_disease_suffering BOOLEAN,
   under_treatment_mental_disease BOOLEAN,
   mental_current_treatment_place VARCHAR(255),
   stroke_hrt_kidney_amp VARCHAR(255),
   dob DATE,
   baby_weighed_at_birth VARCHAR(255),
   birth_weight NUMERIC(7, 3),
   child_received_kmc VARCHAR(255),
   lbw_child_counseled VARCHAR(255),
   child_weighed_last_3_month VARCHAR(255),
   child_height_last_3_month VARCHAR(255),
   child_muac_last_3_month VARCHAR(255),
   weight NUMERIC(7, 3),
   height INTEGER,
   muac NUMERIC(6, 2),
   govt_visited_child BOOLEAN,
   malnutrition_counsel BOOLEAN,
   adequate_diet BOOLEAN,
   consuming_rutf BOOLEAN,
   baby_admitted_rehabilitation_centre BOOLEAN,
   have_vaccination_card VARCHAR(255),
   full_vaccination_received BOOLEAN,
   image text,
   image_uuid text,
   had_diarrhoea_last_2week VARCHAR(255),
   given_drink_for_diarrhoea BOOLEAN,
   fever_last_2weeks VARCHAR(255),
   cough_last_2weeks VARCHAR(255),
   breathing_difficulty_last_2weeks VARCHAR(255),
   seek_treatment BOOLEAN,
   treatment_seek_place VARCHAR(255),
   other_treatment_place VARCHAR(255),
   last_pregnancy_doctor_visit_time VARCHAR(255),
   no_of_doctor_visit VARCHAR(255),
   received_tt_dose VARCHAR(255),
   consumed_ifa_tablets VARCHAR(255),
   last_delivery_place VARCHAR(255),
   avoiding_pregnancy BOOLEAN,
   pregnancy_method VARCHAR(255),
   planning_to_pregnant BOOLEAN,
   family_planning_counsel BOOLEAN,
   screened_for_sickle_cell VARCHAR(255),
   consuming_hydroxyurea BOOLEAN,
   consuming_folic_acid BOOLEAN,
   sputum_examination BOOLEAN,
   cough_more_than_2Weeks BOOLEAN,
   tb_diagnosed BOOLEAN,
   tb_treatment BOOLEAN,
   govt_service_last_6month BOOLEAN,
   govt_service_received VARCHAR(255),
   other_service_received VARCHAR(255),
   screened_for_anemia BOOLEAN,
   iron_pills_given BOOLEAN,
   going_school BOOLEAN,
   opd_care_last_3month BOOLEAN,
   opd_care_reason VARCHAR(255),
   opd_care_other_reason VARCHAR(255),
   opd_treatment_place VARCHAR(255),
   oral_issue_last_3month BOOLEAN,
   oral_treatment_place VARCHAR(255),
   ent_issue_last_3month BOOLEAN,
   ent_treatment_place VARCHAR(255),
   trauma_issue_last_3month BOOLEAN,
   trauma_treatment_place VARCHAR(255),
   eye_issue_last_3month BOOLEAN,
   eye_treatment_place VARCHAR(255),
   palliative_issue_last_3month BOOLEAN,
   palliative_treatment_place VARCHAR(255),
   can_show_abha VARCHAR(255),
   used_abha_last_1year BOOLEAN,
   tele_healthcare_service BOOLEAN,
   created_by integer not null,
   created_on timestamp without time zone not null,
   modified_by integer not null,
   modified_on timestamp without time zone not null
);

CREATE TABLE if not exists sickle_cell_family (
   id SERIAL PRIMARY KEY,
   from_imt_family BOOLEAN,
   family_id VARCHAR(255),
   house_number VARCHAR(255),
   location_id INTEGER,
   religion VARCHAR(255),
   caste VARCHAR(255),
   bpl_flag BOOLEAN,
   anganwadi_id INTEGER,
   toilet_available_flag BOOLEAN,
   is_verified_flag BOOLEAN,
   state VARCHAR(255),
   assigned_to INTEGER,
   address1 VARCHAR(255),
   address2 VARCHAR(255),
   maa_vatsalya_number VARCHAR(255),
   area_id INTEGER,
   vulnerable_flag BOOLEAN,
   migratory_flag BOOLEAN,
   latitude VARCHAR(255),
   longitude VARCHAR(255),
   rsby_card_number VARCHAR(255),
   comment VARCHAR(4000),
   current_state INTEGER,
   is_report BOOLEAN,
   contact_person_id INTEGER,
   hof_id INTEGER,
   additional_info text,
   currentStateDetail INTEGER,
   merged_with VARCHAR(255),
   anganwadi_update_flag BOOLEAN,
   any_member_cbac_done BOOLEAN,
   type_of_house VARCHAR(255),
   type_of_toilet VARCHAR(255),
   other_toilet VARCHAR(255),
   electricity_availability VARCHAR(255),
   drinking_water_source VARCHAR(255),
   other_water_source VARCHAR(255),
   fuel_for_cooking VARCHAR(255),
   vehicle_details text,
   other_motorized_vehicle VARCHAR(255),
   house_ownership_status VARCHAR(255),
   ration_card_number VARCHAR(255),
   pmjay_card_number VARCHAR(255),
   bpl_card_number VARCHAR(255),
   annual_income VARCHAR(255),
   remarks VARCHAR(255),
   split_from INTEGER,
   is_providing_consent BOOLEAN,
   vulnerability_criteria VARCHAR(255),
   eligible_for_pmjay BOOLEAN,
   other_type_of_house VARCHAR(255),
   ration_card_color VARCHAR(255),
   residence_status VARCHAR(255),
   native_state VARCHAR(255),
   vehicle_availability_flag BOOLEAN,
   pmjay_or_health_insurance VARCHAR(255),
   anyone_travelled_foreign BOOLEAN,
   family_uuid VARCHAR(255),
   outdoor_cooking_practices BOOLEAN,
   waste_disposal_available BOOLEAN,
   handwash_available BOOLEAN,
   storage_meets_standard BOOLEAN,
   water_safety_meets_standard BOOLEAN,
   dishrack_available BOOLEAN,
   complaint_of_insects BOOLEAN,
   complaint_of_rodents BOOLEAN,
   separate_livestock_shelter BOOLEAN,
   no_of_mosquito_nets_available INTEGER,
   waste_disposal_method VARCHAR(255),
   family_status text,
   created_by integer not null,
   created_on timestamp without time zone not null,
   modified_by integer not null,
   modified_on timestamp without time zone not null
);

CREATE TABLE if not exists sickle_cell_member (
   id SERIAL PRIMARY KEY,
   from_imt_member BOOLEAN,
   family_id text,
   first_name text,
   middle_name text,
   last_name text,
   husband_name VARCHAR(255),
   husband_id INTEGER,
   gender text,
   marital_status INTEGER,
   aadhar_number text,
   mobile_number text,
   family_head BOOLEAN,
   dob DATE,
   unique_health_id text,
   ifsc text,
   account_number text,
   is_pregnant BOOLEAN,
   lmp_date DATE,
   normal_cycle_days SMALLINT,
   family_planning_method text,
   fp_insert_operate_date TIMESTAMP,
   state text,
   grandfather_name text,
   emamta_health_id text,
   is_aadhar_verified BOOLEAN,
   is_mobile_verified BOOLEAN,
   is_native BOOLEAN,
   education_status INTEGER,
   is_report BOOLEAN,
   name_as_per_aadhar text,
   aadhaar_reference_key text,
   occupation VARCHAR(255),
   under_treatment_chronic BOOLEAN,
   other_chronic VARCHAR(255),
   other_eye_issue VARCHAR(255),
   mother_name VARCHAR(255),
   nrc_number VARCHAR(255),
   passport_number VARCHAR(255),
   fp_stage VARCHAR(255),
   merged_from_family_id VARCHAR(255),
   agreed_to_share_aadhar BOOLEAN,
   aadhar_status VARCHAR(255),
   year_of_wedding SMALLINT,
   date_of_wedding DATE,
   jsy_payment_given BOOLEAN,
   is_early_registration BOOLEAN,
   mother_id INTEGER,
   jsy_beneficiary BOOLEAN,
   iay_beneficiary BOOLEAN,
   kpsy_beneficiary BOOLEAN,
   chiranjeevi_yojna_beneficiary BOOLEAN,
   haemoglobin NUMERIC(6,2),
   weight NUMERIC(7,3),
   edd TIMESTAMP,
   anc_visit_dates text,
   immunisation_given text,
   blood_group VARCHAR(255),
   place_of_birth text,
   birth_weight NUMERIC(7,3),
   complementary_feeding_started BOOLEAN,
   last_method_of_contraception VARCHAR(255),
   is_high_risk_case BOOLEAN,
   cur_preg_reg_det_id INTEGER,
   cur_preg_reg_date TIMESTAMP,
   menopause_arrived BOOLEAN,
   sync_status VARCHAR(255),
   is_iucd_removed BOOLEAN,
   iucd_removal_date TIMESTAMP,
   congenital_anomaly VARCHAR(255),
   chronic_disease text,
   current_disease text,
   eye_issue text,
   last_delivery_date TIMESTAMP,
   hysterectomy_done BOOLEAN,
   child_nrc_cmtc_status VARCHAR(255),
   last_delivery_outcome VARCHAR(255),
   previous_pregnancy_complication VARCHAR(255),
   remarks VARCHAR(255),
   additional_info text,
   suspected_cp BOOLEAN,
   npcb_screening_date DATE,
   fhsr_phone_verified BOOLEAN,
   basic_state text,
   eligible_couple_date DATE,
   current_gravida SMALLINT,
   current_para SMALLINT,
   family_planning_health_infrastructure bigint,
   relation_with_hof VARCHAR(255),
   member_uuid VARCHAR(255),
   vulnerable_flag BOOLEAN,
   abha_status VARCHAR(255),
   health_id VARCHAR(255),
   health_id_number VARCHAR(255),
   health_insurance BOOLEAN,
   scheme_detail VARCHAR(255),
   is_personal_history_done BOOLEAN,
   pmjay_availability VARCHAR(255),
   alcohol_addiction VARCHAR(255),
   smoking_addiction VARCHAR(255),
   tobacco_addiction VARCHAR(255),
   rch_id VARCHAR(255),
   hospitalized_earlier BOOLEAN,
   alternate_number VARCHAR(255),
   physical_disability VARCHAR(255),
   other_disability VARCHAR(255),
   cataract_surgery VARCHAR(255),
   sickle_cell_status VARCHAR(255),
   pension_scheme VARCHAR(255),
   other_hof_relation VARCHAR(255),
   is_child_going_school BOOLEAN,
   current_studying_standard VARCHAR(255),
   ndhm_health_id VARCHAR(255),
   is_abha_failed BOOLEAN,
   chronic_disease_treatment text,
   other_chronic_disease_treatment VARCHAR(255),
   fp_sub_method VARCHAR(255),
   fp_alternative_main_method VARCHAR(255),
   fp_alternative_sub_method VARCHAR(255),
   member_religion VARCHAR(255),
   not_using_fp_reason VARCHAR(255),
   started_menstruating BOOLEAN,
   planning_for_family BOOLEAN,
   personally_using_fp BOOLEAN,
   created_by integer not null,
   created_on timestamp without time zone not null,
   modified_by integer not null,
   modified_on timestamp without time zone not null
);

