CREATE TABLE if not exists member_anemia_survey_details (
    id SERIAL PRIMARY KEY,
    member_id INTEGER not null,
    family_id INTEGER not null,
    location_id INTEGER not null,
    service_date DATE not null,
    is_pregnant BOOLEAN,
    lmp_date DATE,
    weekly_iron_supplement BOOLEAN,
    is_lactating BOOLEAN,
    delivery_date DATE,
    haemoglobin NUMERIC(6,2),
    weight NUMERIC(7,3),
    anemia_status text,
    done_from text not null,
    created_by integer not null,
    created_on timestamp without time zone not null,
    modified_by integer not null,
    modified_on timestamp without time zone not null
);