CREATE TABLE if not exists malaria_investigation_master
(
  id serial primary key,
  member_id integer NOT NULL,
  family_id integer,
  location_id integer,
  latitude text,
  longitude text,
  service_date timestamp NOT NULL,
  breeding_site_flag boolean,
  breeding_site_location text,
  anopheles_detected boolean,
  anopheles_stage text,
  site_permanence text,
  site_type text,
  other_site_type text,
  recommended_actions text,
  other_recommended_actions text,
  actions_taken text,
  other_actions_taken text,
  structures_found integer,
  eligible_structures integer,
  strc_sprayed_last_12_month integer,
  total_people integer,
  llin_dist_last_12_month integer,
  llin_people_slept integer,
  created_by integer NOT NULL,
  created_on timestamp without time zone NOT NULL,
  modified_by integer,
  modified_on timestamp without time zone
);