DELETE FROM user_menu_item
WHERE menu_config_id IN (
    SELECT id FROM menu_config
    WHERE menu_name IN (
        'FHS Dashboard',
            'MO CHFC Re-Verification',
            'MO Re-Verification - Level 2',
            'Call Center Verification',
            'Manage Anganwadis',
            'Family Moving',
            'FHS Work Progress',
            'RCH Data Migration',
            'NCD Screening Dashboard',
            'Referred Patients',
            'PNC Institution Form',
            'Child Service Visit',
            'ANC Service Visit',
            'Manage Migrations',
            'Suspected CP',
            'Location Wise Expected Target',
            'Duplicate Member Verification',
            'Lab Test Admin',
            'Timeline Configuration',
            'Update Family Area',
            'RCH Locations',
            'Team Type Config',
            'Manage Lab Infrastructure',
            'Cluster Management',
            'Suspect List',
            'OPD Lab Test Entry',
            'Lab',
            'Spatial Distribution Of Cases',
            'Hospital Admission',
            'Contact Tracing',
            'Search Techo Members',
            'Rapid Response Dashboard',
            'Track 104 Calls',
            'Manage OPD Lab Test',
            'Out-Patient Treatment (OPD)',
            'Dynamic Form Builder',
            'DTC Interface',
            'Covid Travellers Screening',
            'Form S',
            'Manage Teams',
            'Configure RBSK defects',
            'Manage Schools',
            'Staff Sms Configuration',
            'Manage Location Wards',
            'Timeline Configuration',
            'Sickle Cell Screening',
            'Content Preview Config',
            'Tip Of The Day',
            'Call Center Dashboard',
            'Health Infrastructure Approval',
            'Dr. Techo User Approval',
            'Manage Volunteers',
            'Card Configuration',
            'Manage FAQ',
            'Query Excel Sheet Generator',
            'Family Planning Service Visit',
            'RCH Register',
            'Command and Control Center',
            'NCD Location-wise Report',
            'Place of Service Delivery',
            'Helpdesk Tool - Search',
            'National Programme For Control of Blindness',
            'Service Register',
            'User GEO Services',
            'Temp - Chiranjeevi Deliveries',
            'Upload Document',
            'TEMP - UPDATE PREGNANCY SERVICE DATE',
            'Mobile Library',
            'Widgets management',
            'Facility Performance'
    )
);


DELETE FROM menu_config
WHERE menu_name IN (
    'FHS Dashboard',
        'MO CHFC Re-Verification',
        'MO Re-Verification - Level 2',
        'Call Center Verification',
        'Manage Anganwadis',
        'Family Moving',
        'FHS Work Progress',
        'RCH Data Migration',
        'NCD Screening Dashboard',
        'Referred Patients',
        'PNC Institution Form',
        'Child Service Visit',
        'ANC Service Visit',
        'Manage Migrations',
        'Suspected CP',
        'Location Wise Expected Target',
        'Duplicate Member Verification',
        'Lab Test Admin',
        'Timeline Configuration',
        'Update Family Area',
        'RCH Locations',
        'Team Type Config',
        'Manage Lab Infrastructure',
        'Cluster Management',
        'Suspect List',
        'OPD Lab Test Entry',
        'Lab',
        'Spatial Distribution Of Cases',
        'Hospital Admission',
        'Contact Tracing',
        'Search Techo Members',
        'Rapid Response Dashboard',
        'Track 104 Calls',
        'Manage OPD Lab Test',
        'Out-Patient Treatment (OPD)',
        'Dynamic Form Builder',
        'DTC Interface',
        'Covid Travellers Screening',
        'Form S',
        'Manage Teams',
        'Configure RBSK defects',
        'Manage Schools',
        'Staff Sms Configuration',
        'Manage Location Wards',
        'Timeline Configuration',
        'Sickle Cell Screening',
        'Content Preview Config',
        'Tip Of The Day',
        'Call Center Dashboard',
        'Health Infrastructure Approval',
        'Dr. Techo User Approval',
        'Manage Volunteers',
        'Card Configuration',
        'Manage FAQ',
        'Query Excel Sheet Generator',
        'Family Planning Service Visit',
        'RCH Register',
        'Command and Control Center',
        'NCD Location-wise Report',
        'Place of Service Delivery',
        'Helpdesk Tool - Search',
        'National Programme For Control of Blindness',
        'Service Register',
        'User GEO Services',
        'Temp - Chiranjeevi Deliveries',
        'Upload Document',
        'TEMP - UPDATE PREGNANCY SERVICE DATE',
        'Mobile Library',
        'Widgets management',
        'Facility Performance'
);



