ALTER TABLE public.imt_family
  DROP COLUMN IF EXISTS anganwadi_id,
  DROP COLUMN IF EXISTS bpl_flag,
  DROP COLUMN IF EXISTS caste,
  DROP COLUMN IF EXISTS maa_vatsalya_number,
  DROP COLUMN IF EXISTS rsby_card_number,
  DROP COLUMN IF EXISTS emamta_location_id,
  DROP COLUMN IF EXISTS emamta_location_parent_id,
  DROP COLUMN IF EXISTS anganwadi_update_flag,
  DROP COLUMN IF EXISTS pmjay_card_number,
  DROP COLUMN IF EXISTS bpl_card_number,
  DROP COLUMN IF EXISTS color_of_ration_card,
  DROP COLUMN IF EXISTS have_pmjay_card_number,
  DROP COLUMN IF EXISTS eligible_for_pmjay,
  DROP COLUMN IF EXISTS ration_card_color,
  DROP COLUMN IF EXISTS pmjay_or_health_insurance;