UPDATE menu_config
SET active = false
where menu_name in (
	'GVK : Call Effectiveness Reports',
	'Manage PNC visit',
	'Referred Patients',
	'FHS Dashboard',
    'MO CHFC Re-Verification',
    'MO Re-Verification - Level 2',
    'Call Center Verification',
    'Manage Anganwadis',
    'NCD Screening Dashboard',
    'PNC Institution Form',
    'Child Service Visit',
    'ANC Service Visit',
    'Suspected CP',
    'Duplicate Member Verification',
    'Lab Test Admin',
    'Team Type Config',
    'Manage Lab Infrastructure',
    'Cluster Management',
    'Suspect List',
    'OPD Lab Test Entry',
    'Lab',
    'Spatial Distribution Of Cases',
    'Hospital Admission',
    'Contact Tracing',
    'Search Techo Members',
    'Rapid Response Dashboard',
    'Track 104 Calls',
    'Manage OPD Lab Test',
    'Out-Patient Treatment (OPD)',
    'Dynamic Form Builder',
    'DTC Interface',
    'Covid Travellers Screening',
    'Form S',
    'Manage Teams',
    'Configure RBSK defects',
    'Manage Schools',
    'Staff Sms Configuration',
    'Sickle Cell Screening',
    'Content Preview Config',
    'Tip Of The Day',
    'Call Center Dashboard',
    'Health Infrastructure Approval',
    'Dr. Techo User Approval',
    'Manage Volunteers',
    'Card Configuration',
    'Manage FAQ',
    'RCH Register',
    'Command and Control Center',
    'NCD Location-wise Report',
    'Place of Service Delivery',
    'Helpdesk Tool - Search',
    'National Programme For Control of Blindness',
    'Service Register',
    'User GEO Services',
    'Temp - Chiranjeevi Deliveries',
    'Upload Document',
    'TEMP - UPDATE PREGNANCY SERVICE DATE',
    'Mobile Library'
)