UPDATE public.event_configuration
SET state = 'INACTIVE'
WHERE name IN (
    'ASHA SAM Screening Event',
    'FSAM To CMAM Transfer',
    'FHW Sam Screening Referral',
    'Update member basic detail',
    'MO Performance data update',
    'RCH Data Push - Data collection',
    'last 7 days not enter any data scheduler',
    'Notification Generation for ASHA',
    'GVK ANM service verification',
    'Fhw rank calculation based on his performance',
    'Anmol - RCH - Generate eligible couple - case 1',
    'SMS daily carrier status update',
    'Nutrition_Analytics',
    'Nutrition Defaulter For Follow up',
    'CMAM Followup',
    'Task completion rate generation',
    'Distinct Performance Dashboard',
    'Widget high risk data entry',
    'Scheduler Exception SMS',
    'Family location assign query',
    'User login rate daily updation',
    'Member SMS Genrator',
    'NCD Analytics',
    'Ncd Services Provided During Year (HMIS)',
    'CM Dashboard OPD IPD Data Generation',
    'Nutrition Defaulter For Daily Weight',
    'Asha ANC Service Visit',
    'IDSP Member Screening Report Date Wise Details',
    'PMSMA Services Statistics Analytics',
    'TEST',
    'CM Dashboard DDO KPI Data Generation',
    'Duplicate Entry Generator',
    'PMSMA Services Statistics Analytics - yearly',
    'SMS for not login',
    'CM Dashboard Infant and maternal death line list generation',
    'MO Sms notification temp',
    'GVK Call center dashboard analytics data generation',
    'GVK EMERI - Pregnancy verification data entry',
    'CM Dashboard Daily Report Data generation',
    'Gvk high risk data entry',
    'CHFC Family verification - Add to GVK & MO verification',
    'GVK - Due Service MO',
    'Geriatrics Info Update',
    'CM Dashboard IMR MMR',
    'SAM Screening Monthly Alert Generation',
    'Iron Deficiency Due Date SMS Event For ANC Form',
    'Covid Lab Test Case History',
    'SMS send To Beneficiary',
    'Update Mobile Notification if DOB of a child is changed',
    'Iron Deficiency Due Date SMS Event For PNC Form',
    'last 4 days not logged in scheduler',
    'CFHC Death Verification MO',
    'ASHA LMP Follow Up Event',
    'SMS Polio 2',
    'Asha Child Service Visit',
    'CMTC Screening Analytics Insertion Event',
    'CFHC Suspected widget',
    'CFHC confirmed widget',
    'Sam Screening Event',
    'Move api request response detail to request response final detail',
    'Rbsk location wise monthly analytics',
    'Asha PNC Visit',
    'cfhc daily Insertion Record Event',
    'ncd_mo_review_members'
);
