alter table child_cmtc_nrc_admission_detail
drop column if exists hemoglobin,
drop column if exists lymphocytes,
drop column if exists eosinophil,
drop column if exists rbs,
drop column if exists urine_creatinine,
drop column if exists urine_pus_cells,
drop column if exists urine_pus_cells_count,
drop column if exists ps_for_mp,
drop column if exists ps_for_mp_value,
drop column if exists monotoux_test,
drop column if exists xray_chest,
drop column if exists esr,
drop column if exists monocytes,
drop column if exists basophils,
drop column if exists urine_glucose,
drop column if exists urine_albumin,
drop column if exists hiv_test,
drop column if exists blood_group,
add column hemoglobin real,
add column lymphocytes real,
add column eosinophil real,
add column rbs real,
add column urine_creatinine text,
add column urine_pus_cells text,
add column urine_pus_cells_count real,
add column ps_for_mp text,
add column ps_for_mp_value text,
add column monotoux_test text,
add column xray_chest real,
add column esr real,
add column monocytes real,
add column basophils real,
add column urine_glucose text,
add column urine_albumin text,
add column hiv_test text,
add column blood_group text