ALTER TABLE public.ncd_member_cbac_detail
DROP COLUMN IF EXISTS age_at_menarche,
ADD COLUMN age_at_menarche integer,
DROP COLUMN IF EXISTS menopause_arrived,
ADD COLUMN menopause_arrived boolean,
DROP COLUMN IF EXISTS duration_of_menopause,
ADD COLUMN duration_of_menopause integer,
DROP COLUMN IF EXISTS pregnant,
ADD COLUMN pregnant boolean,
DROP COLUMN IF EXISTS lactating,
ADD COLUMN lactating boolean,
DROP COLUMN IF EXISTS regular_periods,
ADD COLUMN regular_periods boolean,
DROP COLUMN IF EXISTS lmp,
ADD COLUMN lmp timestamp without time zone,
DROP COLUMN IF EXISTS bleeding,
ADD COLUMN bleeding text,
DROP COLUMN IF EXISTS associated_with,
ADD COLUMN associated_with text,
DROP COLUMN IF EXISTS remarks,
ADD COLUMN remarks text,
DROP COLUMN IF EXISTS diagnosed_for_hypertension,
ADD COLUMN diagnosed_for_hypertension boolean,
DROP COLUMN IF EXISTS under_treatement_for_hypertension,
ADD COLUMN under_treatement_for_hypertension boolean,
DROP COLUMN IF EXISTS diagnosed_for_diabetes,
ADD COLUMN diagnosed_for_diabetes boolean,
DROP COLUMN IF EXISTS under_treatement_for_diabetes,
ADD COLUMN under_treatement_for_diabetes boolean,
DROP COLUMN IF EXISTS diagnosed_for_heart_diseases,
ADD COLUMN diagnosed_for_heart_diseases boolean,
DROP COLUMN IF EXISTS under_treatement_for_heart_diseases,
ADD COLUMN under_treatement_for_heart_diseases boolean,
DROP COLUMN IF EXISTS diagnosed_for_stroke,
ADD COLUMN diagnosed_for_stroke boolean,
DROP COLUMN IF EXISTS under_treatement_for_stroke,
ADD COLUMN under_treatement_for_stroke boolean,
DROP COLUMN IF EXISTS diagnosed_for_kidney_failure,
ADD COLUMN diagnosed_for_kidney_failure boolean,
DROP COLUMN IF EXISTS under_treatement_for_kidney_failure,
ADD COLUMN under_treatement_for_kidney_failure boolean,
DROP COLUMN IF EXISTS diagnosed_for_non_healing_wound,
ADD COLUMN diagnosed_for_non_healing_wound boolean,
DROP COLUMN IF EXISTS under_treatement_for_non_healing_wound,
ADD COLUMN under_treatement_for_non_healing_wound boolean,
DROP COLUMN IF EXISTS diagnosed_for_copd,
ADD COLUMN diagnosed_for_copd boolean,
DROP COLUMN IF EXISTS under_treatement_for_copd,
ADD COLUMN under_treatement_for_copd boolean,
DROP COLUMN IF EXISTS diagnosed_for_asthama,
ADD COLUMN diagnosed_for_asthama boolean,
DROP COLUMN IF EXISTS under_treatement_for_asthama,
ADD COLUMN under_treatement_for_asthama boolean,
DROP COLUMN IF EXISTS diagnosed_for_oral_cancer,
ADD COLUMN diagnosed_for_oral_cancer boolean,
DROP COLUMN IF EXISTS under_treatement_for_oral_cancer,
ADD COLUMN under_treatement_for_oral_cancer boolean,
DROP COLUMN IF EXISTS diagnosed_for_breast_cancer,
ADD COLUMN diagnosed_for_breast_cancer boolean,
DROP COLUMN IF EXISTS under_treatement_for_breast_cancer,
ADD COLUMN under_treatement_for_breast_cancer boolean,
DROP COLUMN IF EXISTS diagnosed_for_cervical_cancer,
ADD COLUMN diagnosed_for_cervical_cancer boolean,
DROP COLUMN IF EXISTS under_treatement_for_cervical_cancer,
ADD COLUMN under_treatement_for_cervical_cancer boolean,
DROP COLUMN IF EXISTS height,
ADD COLUMN height integer,
DROP COLUMN IF EXISTS weight,
ADD COLUMN weight real,
DROP COLUMN IF EXISTS bmi,
ADD COLUMN bmi real;