DROP TABLE IF EXISTS rch_asha_child_service_master;
CREATE TABLE rch_asha_child_service_master (
    id bigserial,
    member_id bigint NOT NULL,
    family_id bigint NOT NULL,
    latitude text,
    longitude text,
    mobile_start_date timestamp without time zone NOT NULL,
    mobile_end_date timestamp without time zone NOT NULL,
    location_id bigint NOT NULL,
    location_hierarchy_id bigint NOT NULL,
    notification_id bigint,
    created_by bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_on timestamp without time zone,
    service_date date,
    service_place text,
    type_of_hospital bigint,
    health_infrastructure_id bigint,
    is_alive boolean,
    death_date date,
    death_place text,
    death_reason text,
    other_death_reason text,
    unable_to_drink_breastfeed boolean,
    vomit_everything boolean,
    have_convulsions boolean,
    have_cough_or_fast_breathing boolean,
    cough_days integer,
    breath_in_one_minute integer,
    have_chest_indrawing boolean,
    have_more_stools_diarrhea boolean,
    diarrhea_days integer,
    blood_in_stools boolean,
    sunken_eyes boolean,
    irritable_or_restless boolean,
    lethargic_or_unconsious boolean,
    skin_behaviour_after_pinching text,
    drinking_behaviour text,
    have_fever boolean,
    fever_days integer,
    fever_present_each_day boolean,
    is_neck_stiff boolean,
    have_fever_on_service boolean,
    have_palmer_poller text,
    have_severe_wasting boolean,
    have_edema_both_feet boolean,
    weight real,
    date_of_weight date,
    mother_informed_about_grade boolean,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS rch_asha_pnc_master;
CREATE TABLE rch_asha_pnc_master (
    id bigserial,
    member_id bigint NOT NULL,
    family_id bigint NOT NULL,
    latitude text,
    longitude text,
    mobile_start_date timestamp without time zone NOT NULL,
    mobile_end_date timestamp without time zone NOT NULL,
    location_id bigint NOT NULL,
    location_hierarchy_id bigint NOT NULL,
    notification_id bigint,
    created_by bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_on timestamp without time zone,
    pregnancy_reg_det_id bigint,
    pnc_no integer,
    service_date date,
    service_place text,
    type_of_hospital bigint,
    health_infrastructure_id bigint,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS rch_asha_pnc_mother_master;
CREATE TABLE rch_asha_pnc_mother_master (
    id bigserial,
    pnc_master_id bigint,
    mother_id bigint,
    created_by bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_on timestamp without time zone,
    is_alive boolean,
    death_date date,
    death_place text,
    death_reason text,
    other_death_reason text,
    bleeding_continues boolean,
    pads_changed_in_24_hours integer,
    foul_smell_discharge boolean,
    abnormal_behaviour boolean,
    have_fever boolean,
    have_visual_disturbances boolean,
    difficulty_in_breastfeeding boolean,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS rch_asha_pnc_mother_problem_present;
CREATE TABLE rch_asha_pnc_mother_problem_present (
    pnc_id bigint NOT NULL,
    problem text NOT NULL,
    PRIMARY KEY (pnc_id, problem),
    FOREIGN KEY (pnc_id)
        REFERENCES rch_asha_pnc_mother_master (id) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE NO ACTION
);

DROP TABLE IF EXISTS rch_asha_pnc_child_master;
CREATE TABLE rch_asha_pnc_child_master (
    id bigserial,
    pnc_master_id bigint,
    child_id bigint,
    created_by bigint NOT NULL,
    created_on timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_on timestamp without time zone,
    is_alive boolean,
    death_date date,
    death_place text,
    death_reason text,
    other_death_reason text,
    cry text,
    fed_less_than_usual text,
    sucking text,
    throws_milk boolean,
    hands_feets_cold boolean,
    skin text,
    skin_pustules boolean,
    have_chest_indrawing boolean,
    umbilicus text,
    abdomen text,
    tempreature real,
    limbs_neck text,
    eyes text,
    weight real,
    weight_date date,
    PRIMARY KEY (id)
);