
-- Inserting new keys
insert into internationalization_label_master(country, key, language, created_by, created_on, custom3b, text, translation_pending) VALUES
-- English Language
('US', 'Age(atpresent)_web', 'EN', 'Administrator', now(), false, 'Age(at present)', false),
('US', 'Age(atthetimeofmarriage)_web', 'EN', 'Administrator', now(), false, 'Age(at the time of marriage)', false),
('US', 'TotalNumberofChildBirths_web', 'EN', 'Administrator', now(), false, 'Total Number of Child Births', false),
('US', 'YoungestChildInformation_web', 'EN', 'Administrator', now(), false, 'Youngest Child Information', false),
('US', 'FIPV1_web', 'EN', 'Administrator', now(), false, 'F IPV 1', false),
('US', 'FIPV2_web', 'EN', 'Administrator', now(), false, 'F IPV 2', false),
('US', 'VACCINATIONDETAILS_web', 'EN', 'Administrator', now(), false, 'VACCINATION DETAILS', false),
('US', 'BirthDate_web', 'EN', 'Administrator', now(), false, 'Birth Date', false),
('US', 'BirthPlace_web', 'EN', 'Administrator', now(), false, 'Birth Place', false),
('US', 'FullyImmunizedinTwelveMonths?_web', 'EN', 'Administrator', now(), false, 'Fully Immunized in Twelve Months?', false),
('US', 'FullyImmunizedinTwoYears?_web', 'EN', 'Administrator', now(), false, 'Fully Immunized in Two Years?', false),
('US', 'BreastfeduntilSixMonths_web', 'EN', 'Administrator', now(), false, 'Breastfed until Six Months', false),
('US', 'VitaminADose_web', 'EN', 'Administrator', now(), false, 'Vitamin A Dose', false),
('US', 'OPVBooster_web', 'EN', 'Administrator', now(), false, 'OPV Booster', false),
('US', 'DPTBooster1_web', 'EN', 'Administrator', now(), false, 'DPT Booster 1', false),
('US', 'DPTBooster2(5yrs)_web', 'EN', 'Administrator', now(), false, 'DPT Booster 2 (5 yrs)', false),
('US', 'DPTBooster_web', 'EN', 'Administrator', now(), false, 'DPT Booster', false),
('US', 'DPTBooster2_web', 'EN', 'Administrator', now(), false, 'DPT Booster 2', false),
('US', 'AdverseEffect_web', 'EN', 'Administrator', now(), false, 'Adverse Effect', false),
('US', 'VaccinationDetails_web', 'EN', 'Administrator', now(), false, 'Vaccination Details', false),
('US', 'PregnancyWeekNumberattheTimeofRegistration_web', 'EN', 'Administrator', now(), false, 'Pregnancy Week Number at the Time of Registration', false),
('US', 'Registeredwithin12WeeksofPregnancy_web', 'EN', 'Administrator', now(), false, 'Registered within 12 Weeks of Pregnancy', false),
('US', 'ExaminationDetails_web', 'EN', 'Administrator', now(), false, 'Examination Details', false),
('US', 'Date_web', 'EN', 'Administrator', now(), false, 'Date', false),
('US', 'IFATablets_web', 'EN', 'Administrator', now(), false, 'IFA Tablets', false),
('US', 'FoetalHeight(cm)_web', 'EN', 'Administrator', now(), false, 'Foetal Height(cm)', false),
('US', 'IsInfantAlive?_web', 'EN', 'Administrator', now(), false, 'Is Infant Alive?', false),
('US', 'IsReferralDone?_web', 'EN', 'Administrator', now(), false, 'Is Referral Done?', false),
('US', 'DangerSigns_web', 'EN', 'Administrator', now(), false, 'Danger Signs', false),
('US', 'CongenitalDeformities_web', 'EN', 'Administrator', now(), false, 'Congenital Deformities', false),
('US', 'InfantBreastfeedingStartedin1HourofBirth?_web', 'EN', 'Administrator', now(), false, 'Infant Breastfeeding Started in 1 Hour of Birth?', false),
('US', 'NumberofIFATabletsGiven_web', 'EN', 'Administrator', now(), false, 'Number of IFA Tablets Given', false),
('US', 'IsMotherAlive?_web', 'EN', 'Administrator', now(), false, 'Is Mother Alive?', false),
('US', 'RegistrationDate_web', 'EN', 'Administrator', now(), false, 'Registration Date', false),
('US', 'EligibleCoupleDate_web', 'EN', 'Administrator', now(), false, 'Eligible Couple Date', false),
('US', 'FolicAcidTablets_web', 'EN', 'Administrator', now(), false, 'Folic Acid Tablets', false),
-- Gujarati Language
('IN', 'Age(atpresent)_web', 'GU', 'Administrator', now(), false, 'ઉંમર (હાલમાં)', false),
('IN', 'Age(atthetimeofmarriage)_web', 'GU', 'Administrator', now(), false, 'ઉંમર (લગ્ન સમયે)', false),
('IN', 'TotalNumberofChildBirths_web', 'GU', 'Administrator', now(), false, 'કુલ બાળકના જન્મની સંખ્યા', false),
('IN', 'YoungestChildInformation_web', 'GU', 'Administrator', now(), false, 'સૌથી નાની બાળ માહિતી', false),
('IN', 'FIPV1_web', 'GU', 'Administrator', now(), false, 'એફ આઇપીવી 1', false),
('IN', 'FIPV2_web', 'GU', 'Administrator', now(), false, 'એફ આઇપીવી 2', false),
('IN', 'VACCINATIONDETAILS_web', 'GU', 'Administrator', now(), false, 'રસીકરણ વિગતો', false),
('IN', 'BirthDate_web', 'GU', 'Administrator', now(), false, 'જન્મ તારીખ', false),
('IN', 'BirthPlace_web', 'GU', 'Administrator', now(), false, 'જન્મ સ્થળ', false),
('IN', 'FullyImmunizedinTwelveMonths?_web', 'GU', 'Administrator', now(), false, 'બાર મહિનામાં સંપૂર્ણપણે રસીકરણ?', false),
('IN', 'FullyImmunizedinTwoYears?_web', 'GU', 'Administrator', now(), false, 'બે વર્ષમાં સંપૂર્ણપણે રસીકરણ?', false),
('IN', 'BreastfeduntilSixMonths_web', 'GU', 'Administrator', now(), false, 'છ મહિના સુધી સ્તનપાન', false),
('IN', 'VitaminADose_web', 'GU', 'Administrator', now(), false, 'વિટામિન એ ડોઝ', false),
('IN', 'OPVBooster_web', 'GU', 'Administrator', now(), false, 'ઓપીવી બુસ્ટર', false),
('IN', 'DPTBooster1_web', 'GU', 'Administrator', now(), false, 'ડીપીટી બુસ્ટર 1', false),
('IN', 'DPTBooster2(5yrs)_web', 'GU', 'Administrator', now(), false, 'ડીપીટી બુસ્ટર 2 (5 વર્ષ)', false),
('IN', 'DPTBooster_web', 'GU', 'Administrator', now(), false, 'ડીપીટી બુસ્ટર', false),
('IN', 'DPTBooster2_web', 'GU', 'Administrator', now(), false, 'ડીપીટી બુસ્ટર 2', false),
('IN', 'AdverseEffect_web', 'GU', 'Administrator', now(), false, 'પ્રતિકૂળ અસર', false),
('IN', 'VaccinationDetails_web', 'GU', 'Administrator', now(), false, 'રસીકરણ વિગતો', false),
('IN', 'PregnancyWeekNumberattheTimeofRegistration_web', 'GU', 'Administrator', now(), false, 'નોંધણી સમયે ગર્ભાવસ્થા સપ્તાહ નંબર', false),
('IN', 'Registeredwithin12WeeksofPregnancy_web', 'GU', 'Administrator', now(), false, 'ગર્ભાવસ્થાના 12 અઠવાડિયાની અંદર નોંધાયેલ', false),
('IN', 'ExaminationDetails_web', 'GU', 'Administrator', now(), false, 'પરીક્ષાની વિગતો', false),
('IN', 'Date_web', 'GU', 'Administrator', now(), false, 'તારીખ', false),
('IN', 'IFATablets_web', 'GU', 'Administrator', now(), false, 'આઇએફએ ગોળીઓ', false),
('IN', 'FoetalHeight(cm)_web', 'GU', 'Administrator', now(), false, 'ગર્ભની ઊંચાઈ(સે.મી.)', false),
('IN', 'IsInfantAlive?_web', 'GU', 'Administrator', now(), false, 'શું શિશુ જીવંત છે?', false),
('IN', 'IsReferralDone?_web', 'GU', 'Administrator', now(), false, 'રેફરલ થઈ ગયું છે?', false),
('IN', 'DangerSigns_web', 'GU', 'Administrator', now(), false, 'ડેન્જર સંકેતો', false),
('IN', 'CongenitalDeformities_web', 'GU', 'Administrator', now(), false, 'જન્મજાત ખોડ', false),
('IN', 'InfantBreastfeedingStartedin1HourofBirth?_web', 'GU', 'Administrator', now(), false, '1 કલાકના જન્મથી શિશુ સ્તનપાન શરૂ થયું?', false),
('IN', 'NumberofIFATabletsGiven_web', 'GU', 'Administrator', now(), false, 'આપેલ આઈ.એફ.એ. ગોળીઓની સંખ્યા', false),
('IN', 'IsMotherAlive?_web', 'GU', 'Administrator', now(), false, 'શું માતા જીવંત છે?', false),
('IN', 'RegistrationDate_web', 'GU', 'Administrator', now(), false, 'નોંધણી તારીખ', false),
('IN', 'EligibleCoupleDate_web', 'GU', 'Administrator', now(), false, 'પાત્ર દંપતી તારીખ', false),
('IN', 'FolicAcidTablets_web', 'GU', 'Administrator', now(), false, 'ફોલિક એસિડ ગોળીઓ', false)
ON conflict on constraint internationalization_label_master_pkey
DO NOTHING;
