---- for issue https://argusgit.argusoft.com/mhealth-projects/imtecho/issues/3027
--
--begin;
--
--ALTER TABLE IF EXISTS "anmol_child_pnc"
--ALTER COLUMN "infant_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
-- insert soh element modules
--ALTER TABLE IF EXISTS "anmol_child_registration"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "anmol_child_tracking_medical"
--ALTER COLUMN "child_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "anmol_mother_infants"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "aww_child_service_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_cmtc_nrc_admission_detail"
--ALTER COLUMN "weight_at_admission" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_cmtc_nrc_discharge_detail"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_cmtc_nrc_follow_up"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_cmtc_nrc_mo_verification"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_cmtc_nrc_weight_detail"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "ncd_member_cbac_detail"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_anc_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_child_analytics_details"
--ALTER COLUMN "birth_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_child_service_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_pnc_child_master"
--ALTER COLUMN "child_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_sam_screening_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "cm_dashboard_high_risk_mcomplication_details"
--ALTER COLUMN "percentColWeightLessThan45kg" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_nutrition_sam_screening_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_nutrition_cmam_followup"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "anmol_mother_anc"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "imt_member"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3),
--ALTER COLUMN "birth_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "child_analytics_details"
--ALTER COLUMN "birth_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "anmol_mother_registration"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_asha_child_service_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_asha_pnc_child_master"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_anc_master_archive"
--ALTER COLUMN "weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
--begin;
--
--ALTER TABLE IF EXISTS "rch_wpd_child_master"
--ALTER COLUMN "birth_weight" SET DATA TYPE NUMERIC(7, 3);
--
--commit;
