CREATE TABLE if not exists rch_child_analytics_details
(
  id serial NOT NULL ,
  member_state text,
  member_id integer,
  first_name text,
  middle_name text,
  last_name text,
  member_name text,
  gender text,
  wpd_child_id integer,
  native_loc_id integer,
  delivery_location_id integer,
  loc_id integer,
  dob date,
  dob_month_year date,
  financial_year text,
  death_date date,
  death_location_id integer,
  no_of_days_in_death integer,
  birth_weight numeric(6,2),
  mother_id integer,
  vitamin_k date,
  vitamin_k_loc bigint,
  bcg date,
  bcg_loc integer,
  dpt1 date,
  dpt1_loc integer,
  penta1 date,
  penta1_loc integer,
  opv0 date,
  opv0_loc integer,
  opv1 date,
  opv1_loc integer,
  hep_b date,
  hep_b_loc integer,
  dpt2 date,
  dpt2_loc integer,
  penta2 date,
  penta2_loc integer,
  opv2 date,
  opv2_loc integer,
  dpt3 date,
  dpt3_loc integer,
  penta3 date,
  penta3_loc integer,
  opv3 date,
  opv3_loc integer,
  f_ipv1 date,
  f_ipv1_loc integer,
  f_ipv2 date,
  f_ipv2_loc integer,
  measles date,
  measles_loc integer,
  measles_rubella date,
  measles_rubella_loc integer,
  opv_booster date,
  opv_booster_loc integer,
  dpt_booster date,
  dpt_booster_loc integer,
  measles_2 date,
  measles_2_loc integer,
  measles_rubella_2 date,
  measles_rubella_2_loc integer,
  measles_or_rubella_1 date,
  measles_or_rubella_1_loc integer,
  measles_or_rubella_2 date,
  measles_or_rubella_2_loc integer,
  rota_virus_1 date,
  rota_virus_1_loc bigint,
  rota_virus_2 date,
  rota_virus_2_loc bigint,
  rota_virus_3 date,
  rota_virus_3_loc bigint,
  is_infant_death boolean,
  age_of_mother smallint,
  is_early_reg boolean,
  gravida smallint,
  day_of_delivery integer,
  is_birth_defect_screened boolean,
  has_birth_defects boolean,
  has_neural_tube_def boolean,
  has_downs_syndrome boolean,
  has_cleft_lip boolean,
  has_talipes boolean,
  has_develop_mental_dysplasia_of_hip boolean,
  has_congenital_cataract boolean,
  has_congenital_deafness boolean,
  has_congenital_heart_disease boolean,
  has_retinopathy_of_prematurity boolean,
  has_any_other_birth_defect boolean,
  has_club_foot boolean,
  is_refer boolean,
  has_asphyxia_death boolean,
  has_pnuemonia_death boolean,
  has_diarhoeaa_death boolean,
  has_measles_death boolean,
  has_high_fever_death boolean,
  has_other_death boolean,
  has_lbw_death boolean,
  has_done_breast_feeding_within_one_hour boolean,
  fully_immunization_in_number_of_month smallint,
  full_immunization_date date,
  received_allvaccines boolean,
  is_sam_child boolean,
  sam_child_date timestamp without time zone,
  last_child_service_date date,
  family_id text,
  mam_child integer,
  mam_child_date timestamp without time zone,
  sam_child_normal integer,
  sam_child_normal_date timestamp without time zone,
  death_reason bigint,
  complete_immunization_date date,
  complete_immunization_in_number_of_month smallint,
  full_immunization_date_exclude_bcg date,
  last_sd_score text,
  last_sd_score_date date,
  live_birth_no smallint,
  overdue_immunisation text,
  high_risk_reasons text,
  CONSTRAINT rch_child_analytics_details1_pkey PRIMARY KEY (id)
);

DO $$
BEGIN
    BEGIN
       alter table rch_child_analytics_details add column high_risk_reasons text;
    EXCEPTION
        WHEN duplicate_column THEN RAISE NOTICE 'column already exists';
    END;
END;
$$;