drop index if exists idsp_member_screening_details_member_id_idx;
CREATE INDEX idsp_member_screening_details_member_id_idx
ON public.idsp_member_screening_details
USING btree (member_id);

drop index if exists idsp_member_screening_details_member_id_service_date_idx;
CREATE INDEX idsp_member_screening_details_member_id_service_date_idx
ON public.idsp_member_screening_details
USING btree (member_id, service_date);

drop index if exists idsp_family_screening_details_family_id_idx;
CREATE INDEX idsp_family_screening_details_family_id_idx
ON public.idsp_family_screening_details
USING btree (family_id);

drop index if exists idsp_family_screening_details_family_id_service_date_idx;
CREATE INDEX idsp_family_screening_details_family_id_service_date_idx
ON public.idsp_family_screening_details
USING btree (family_id, service_date);

drop index if exists idsp_2_family_screening_details_family_id_idx;
CREATE INDEX idsp_2_family_screening_details_family_id_idx
ON public.idsp_2_family_screening_details
USING btree (family_id);

drop index if exists idsp_2_family_screening_details_family_id_service_date_idx;
CREATE INDEX idsp_2_family_screening_details_family_id_service_date_idx
ON public.idsp_2_family_screening_details
USING btree (family_id, service_date);

drop index if exists idsp_2_member_screening_details_member_id_idx;
CREATE INDEX idsp_2_member_screening_details_member_id_idx
ON public.idsp_2_member_screening_details
USING btree (member_id);

drop index if exists idsp_2_member_screening_details_member_id_service_date_idx;
CREATE INDEX idsp_2_member_screening_details_member_id_service_date_idx
ON public.idsp_2_member_screening_details
USING btree (member_id, service_date);

drop index if exists covid_travellers_info_member_id_idx;
CREATE INDEX covid_travellers_info_member_id_idx
ON public.covid_travellers_info
USING btree (member_id);

drop index if exists covid_travellers_info_location_id_idx;
CREATE INDEX covid_travellers_info_location_id_idx
ON public.covid_travellers_info
USING btree (location_id);

drop index if exists covid_travellers_info_location_id_modified_on_idx;
CREATE INDEX covid_travellers_info_location_id_modified_on_idx
ON public.covid_travellers_info
USING btree (location_id, modified_on);
